config/routes.rb
Rails.application.routes.draw do
  resources :historic_refinancings
  get 'home/index'
  get 'loans/index'

  resources :refinancings do
    get 'annotation'
  end

  resources :authorizations
  resources :employees
  resources :people

  root 'home#index'

end

app/models/historic_refinancing.rb
class HistoricRefinancing < ActiveRecord::Base
end

app/controllers/historic_refinancings_controller.rb
class HistoricRefinancingsController < ApplicationController
  before_action :set_historic_refinancing, only: [:show, :edit, :update, :destroy]

  # GET /historic_refinancings
  # GET /historic_refinancings.json
  def index
    @historic_refinancings = HistoricRefinancing.all
  end

  # GET /historic_refinancings/1
  # GET /historic_refinancings/1.json
  def show
  end

  # GET /historic_refinancings/new
  def new
    @historic_refinancing = HistoricRefinancing.new
  end

  # GET /historic_refinancings/1/edit
  def edit
  end

  # POST /historic_refinancings
  # POST /historic_refinancings.json
  def create
    @historic_refinancing = HistoricRefinancing.new(historic_refinancing_params)

    respond_to do |format|
      if @historic_refinancing.save
        format.html { redirect_to @historic_refinancing, notice: 'Historic refinancing was successfully created.' }
        format.json { render :show, status: :created, location: @historic_refinancing }
      else
        format.html { render :new }
        format.json { render json: @historic_refinancing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historic_refinancings/1
  # PATCH/PUT /historic_refinancings/1.json
  def update
    respond_to do |format|
      if @historic_refinancing.update(historic_refinancing_params)
        format.html { redirect_to @historic_refinancing, notice: 'Historic refinancing was successfully updated.' }
        format.json { render :show, status: :ok, location: @historic_refinancing }
      else
        format.html { render :edit }
        format.json { render json: @historic_refinancing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historic_refinancings/1
  # DELETE /historic_refinancings/1.json
  def destroy
    @historic_refinancing.destroy
    respond_to do |format|
      format.html { redirect_to historic_refinancings_url, notice: 'Historic refinancing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historic_refinancing
      @historic_refinancing = HistoricRefinancing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def historic_refinancing_params
      params.require(:historic_refinancing).permit(:authorization_origin_id, :refinancing_id, :authorization_new_id)
    end
end

app/helpers/historic_refinancings_helper.rb
module HistoricRefinancingsHelper
end

app/views/historic_refinancings/_form.html.erb
<%= simple_form_for(@historic_refinancing) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :authorization_origin_id %>
    <%= f.input :refinancing_id %>
    <%= f.input :authorization_new_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/historic_refinancings/edit.html.erb
<h1>Editing Historic Refinancing</h1>

<%= render 'form' %>

<%= link_to 'Show', @historic_refinancing %> |
<%= link_to 'Back', historic_refinancings_path %>

app/views/historic_refinancings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Historic Refinancings</h1>

<table>
  <thead>
    <tr>
      <th>Authorization origin</th>
      <th>Refinancing</th>
      <th>Authorization new</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @historic_refinancings.each do |historic_refinancing| %>
      <tr>
        <td><%= historic_refinancing.authorization_origin_id %></td>
        <td><%= historic_refinancing.refinancing_id %></td>
        <td><%= historic_refinancing.authorization_new_id %></td>
        <td><%= link_to 'Show', historic_refinancing %></td>
        <td><%= link_to 'Edit', edit_historic_refinancing_path(historic_refinancing) %></td>
        <td><%= link_to 'Destroy', historic_refinancing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Historic refinancing', new_historic_refinancing_path %>

app/views/historic_refinancings/new.html.erb
<h1>New Historic Refinancing</h1>

<%= render 'form' %>

<%= link_to 'Back', historic_refinancings_path %>

app/views/historic_refinancings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Authorization origin:</strong>
  <%= @historic_refinancing.authorization_origin_id %>
</p>

<p>
  <strong>Refinancing:</strong>
  <%= @historic_refinancing.refinancing_id %>
</p>

<p>
  <strong>Authorization new:</strong>
  <%= @historic_refinancing.authorization_new_id %>
</p>

<%= link_to 'Edit', edit_historic_refinancing_path(@historic_refinancing) %> |
<%= link_to 'Back', historic_refinancings_path %>