config/routes.rb
Rails.application.routes.draw do
  resources :historic_refinancings
  get 'home/index'
  get 'loans/index'

  resources :refinancings do
    get 'annotation'
  end

  resources :authorizations
  resources :employees
  resources :people

  root 'home#index'

end

app/models/refinancing.rb
class Refinancing < ActiveRecord::Base
  before_save :create
  
  belongs_to :employee
  belongs_to :authorization

  accepts_nested_attributes_for :authorization

  enum situation: [:reserved, :annotation, :canceled]

  def create
    self.situation ||= 0
  end

end

app/controllers/refinancings_controller.rb
class RefinancingsController < ApplicationController

  def index
    if params[:search_employee_by_cpf].present?
      @employees = Employee.search_cpf(params[:search_employee_by_cpf]).includes(:authorizations)
    else
      @authorizations = []
    end
  end

  def new
    # Show authorizations
    if params[:authorization].present?
      # Get contract_number checked
      @selected_ids = params[:authorization][:contract_number]
      # Get all authorizations checked
      @authorizations = Authorization.where("contract_number in (?)", @selected_ids)
      # Get the enter values for each contract numbers checked
      auth_params = params[:authorization]
      auth_params[:contract_number].zip(auth_params[:value_solve].reject(&:blank?)).each do |contract_number, value_solve|
          Authorization.where(contract_number: contract_number).update_all(value_solve: value_solve, situation: 2)
      end

      puts "----"
      puts "authorization.ids: #{@authorizations.ids}"
      puts "----"
      @authorizations.ids.each do |auth_id|
        puts "-----"
        puts "auth_id: #{auth_id}"
        puts "-----"
        @historic_refinancing = HistoricRefinancing.create(authorization_origin_id: auth_id)
        #@historic_refinancing = HistoricRefinancing.where(authorization_origin_id: auth_id).update_all(authorization_origin_id: auth_id)
      end

    end
    # Get CPF of employee
    @employee = Employee.search_cpf(params[:search_employee_by_cpf])
    @refinancing = Refinancing.new

  end

  def create
    @refinancing = Refinancing.new(refinancing_params)

    respond_to do |format|
      if @refinancing.save
        format.html { redirect_to @refinancing, notice: 'Refinancing was successfully created.' }
        format.json { render :show, status: :created, location: @refinancing }
      else
        format.html { render :new }
        format.json { render json: @refinancing.errors, status: :unprocessable_entity }
      end
    end

    HistoricRefinancing.where(refinancing_id: nil).update_all(refinancing_id: @refinancing)

  end

  def show
    @refinancing = Refinancing.find(params[:id])
  end

  def annotation
    #Authorization.update_all(situation: 3)

    @new_authorization = Authorization.create(situation: 0)
    #@new_authorization.parcel_value = self.parcel_value
    #@new_authorization.qtd_parcel = self.qtd_parcel
    #@new_authorization.total_value = self.total_value

    respond_to do |format|
      format.js
    end
  end

  private

    def refinancing_params
      params.require(:refinancing).permit(:employee_id, :authorization_id, :contract_number, :situation, :total_value, :parcel_value, :qtd_parcel, :refinancing_date, authorization_attributes: [ :value_solve ])
    end
end

app/helpers/refinancings_helper.rb
module RefinancingsHelper
end

app/views/refinancings/annotation.js.erb
$('.message').html("<div>Sucess!</div>");

app/views/refinancings/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Get refinancing</h3>

<%= form_tag(refinancings_path, name: 'form', :method => :get) do %>
  <h4>Pesquisar Dados Pessoais</h4>
  <div class="form-group">
    <%= text_field_tag "search_employee_by_cpf", nil, placeholder: 'Digite CPF', class: 'form-control mascara-cpf', id: 'search_cpf' %>
  </div>
  <%= submit_tag "Search", :class => 'btn btn-default' %>
<% end %>
<br />
<hr />

<% if params[:search_employee_by_cpf].present? %>
  <h4><b>Results</b></h4>
  <%= form_tag(new_refinancing_path, name: 'form', method: :get) do %>
    <%= hidden_field_tag 'search_employee_by_cpf', params[:search_employee_by_cpf] %>
    <% @employees.each do |employee| %>
      <table class="table table-condensed">
        <tr>
          <th>Name</th>
          <td><%= employee.person.name %></td>
        </tr>
        <tr>
          <th>Matrícula</th>
          <td><%= employee.register %></td>
        </tr>
        <tr>
          <th>CPF</th>
          <td><%= employee.person.cpf %></td>
        </tr>
      </table>

      <hr />

      <table class="table table-condensed table-bordered table-hover">
        <thead>
          <th>&nbsp;</th>
          <th>Contract number</th>
          <th>Value of parcel</th>
          <th>Qtd of parcel</th>
          <th>Total Value</th>
          <th>Value to Solve</th>
        </thead>
        <tbody>
          <% employee.authorizations.each do |authorization| %>
            <tr>
              <td><%= check_box_tag 'authorization[contract_number][]', authorization.contract_number %></td>
              <td><%= authorization.contract_number %></td>
              <td><%= number_to_currency authorization.parcel_value %></td>
              <td><%= authorization.qtd_parcel %></td>
              <td><%= number_to_currency authorization.total_value %></td>
              <td>
                <input class="string required" placeholder="Digit a value" type="text" name="authorization[value_solve][]" id="authorization_value_solve">
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    <% end %>

    <%= submit_tag "Reserve", :class => 'btn btn-primary btn-reserva' %>

  <% end %>
<% end %>

app/views/refinancings/new.html.erb
<h3>Reserve of refinancing</h3>

<table class="table table-condensed table-bordered">
  <tr>
    <td>Name:</td>
    <td><%= @employee.first.person.name %></td>
  </tr>
  <tr>
    <td>CPF:</td>
    <td><%= @employee.first.person.cpf %></td>
  </tr>
</table>

<hr />

<%= simple_form_for(@refinancing) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :employee_id, value: @employee.first.id %>
    <%= f.input :contract_number %>
    <%= f.input :total_value %>
    <%= f.input :parcel_value %>
    <%= f.input :qtd_parcel %>
  </div>

  <hr />

  <h3>Reserved value</h3>
  <table class="table table-condensed table-bordered table-striped">
    <thead>
      <th>Authorization id</th>
      <th>Contract number</th>
      <th>Parcel value X Quantity of Parcels</th>
    </thead>
    <% @authorizations.each do |authorization| %>
      <tbody>
        <tr>
          <td><%= authorization.id %></td>
          <td><%= authorization.contract_number %></td>
          <td><%= number_to_currency authorization.parcel_value %> x <%= authorization.qtd_parcel %></td>
        </tr>
      </tbody>
    <% end %>
  </table>

  <div class="form-actions">
    <%= f.button :submit, "To Reserve" %>
  </div>
<% end %>

app/views/refinancings/show.html.erb
<div class="message"></div>

<p>
  <strong>Name:</strong>
  <%= @refinancing.employee.person.name %>
</p>

<p>
  <strong>Register:</strong>
  <%= @refinancing.employee.register %>
</p>

<p>
  <strong>Contract number:</strong>
  <%= @refinancing.contract_number %>
</p>

<p>
  <strong>Situation:</strong>
  <%= @refinancing.situation %>
</p>

<p>
  <strong>Total value:</strong>
  <%= @refinancing.total_value %>
</p>

<p>
  <strong>Parcel value:</strong>
  <%= @refinancing.parcel_value %>
</p>

<p>
  <strong>Qtd parcel:</strong>
  <%= @refinancing.qtd_parcel %>
</p>

<%= link_to 'Cancel', :back %>
<%= link_to "Annotation", refinancing_annotation_path(@refinancing), remote: true %>

<%= console %>